apiVersion: v1
kind: Service
metadata:
  name: wil-playground-svc
  namespace: dev
spec:
  type: NodePort
  selector:
    app: wil-playground-app
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 8888
