apiVersion: apps/v1
kind: Service
metadata:
  name: wil-playground-svc
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: wil-playground-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
